### ISSUE TITLE
Microsoft.Extensions.Logging dependency not loading for .net 6 console app

### ISSUE THREAD

**Issue by nrcventura** [open-telemetry/opentelemetry-dotnet-instrumentation#385]
Steps to reproduce:
1. Create a .net 6 console application using `dotnet new console`.
2. Use a linux docker container to build and run the application, be sure that the container is using a framework dependent build of the application instead of a self-contained publish.
3. Configure the docker container so that the application is instrumented and that the telemetry is sent to a collector via otlp (over http). Docker compose can be used to configure the required environment variables and volume mount the auto-instrumentation installation directory.
4. See the error about the missing Microsoft.Extensions.Logging dependency
```
app_1        | >>>>>>>>>>>>>>>>>>>>>>> Process: dotnet(1): OpenTelemetry tracer exit.
app_1        | Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Extensions.Logging.Abstractions, Version=2.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
app_1        |
app_1        | File name: 'Microsoft.Extensions.Logging.Abstractions, Version=2.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
app_1        |    at OpenTelemetry.ProviderExtensions.GetResource(BaseProvider baseProvider)
app_1        |    at OpenTelemetry.Exporter.OtlpTraceExporter.get_ProcessResource()
app_1        |    at OpenTelemetry.Exporter.OtlpTraceExporter.Export(Batch`1& activityBatch)
app_1        |    at OpenTelemetry.BatchExportProcessor`1.ExporterProc()
app_1        |    at System.Threading.Thread.StartCallback()
```
Sample dockerfile
```
FROM mcr.microsoft.com/dotnet/runtime:6.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["CrashingApp.csproj", "."]
RUN dotnet restore "./CrashingApp.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "CrashingApp.csproj" -c Release -o /app/build

#FROM build AS publish
#RUN dotnet publish "CrashingApp.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=build /app .
ENTRYPOINT ["dotnet", "build/CrashingApp.dll", "--no-build", "--no-launchsettings"]
```

Sample docker-compose file
```
version: '3'
services:
  app:
    build: .
    ports:
      - "8080:80"
    volumes:
      - <path of local auto instrumentation installation directory>:/tracer-home
    environment:
      DOTNET_ADDITIONAL_DEPS: "/tracer-home/AdditionalDeps"
      DOTNET_SHARED_STORE: "/tracer-home/store"
      OTEL_DOTNET_AUTO_CONSOLE_EXPORTER_ENABLED: "True"
      OTEL_SERVICE_NAME: "CrashingApp"
      OTEL_TRACES_EXPORTER: "otlp"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://collector:4318"
      DOTNET_STARTUP_HOOKS: "/tracer-home/netcoreapp3.1/OpenTelemetry.AutoInstrumentation.StartupHook.dll"
      OTEL_DOTNET_AUTO_HOME: "/tracer-home"
    depends_on:
      - collector
  collector:
    image: otel/opentelemetry-collector-contrib:0.33.0
    volumes:
    - ./otel-config.yaml:/otel-config.yaml
    entrypoint: ["/otelcontribcol"]
    command: ["--config", "/otel-config.yaml"]
    ports:
      - "4318:4318"     # grpc
      - "13133:13133"   # health
```

Sample collector config
```
extensions:
  health_check: {}
receivers:
  otlp:
    protocols:
      http:
exporters:
  logging:
    logLevel: debug
service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [logging]
```

~~The error does not occur if the application is run on windows.~~ I have not tried to reproduce this error on Linux directly or on a Mac. Correction: The problem also occurs on windows.

Adding `<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="2.1.0" />` to the application is the current workaround for when this error occurs.

When discussing this issue in the SIG meeting, the current plan is to add `Microsoft.Extensions.Logging.Abstractions` to the AdditionalDeps.
