### ISSUE TITLE
Support for Npgsql metrics

### ISSUE THREAD

**Issue by Vinaum8** [open-telemetry/opentelemetry-dotnet-instrumentation#4135]
### Package

OpenTelemetry

### Package Version

```
<PackageReference Include="Npgsql" Version="9.0.3" />
<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.3" />
<PackageReference Include="Npgsql.OpenTelemetry" Version="9.0.3" />
<PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.11.2" />
<PackageReference Include="OpenTelemetry.Instrumentation.EntityFrameworkCore" Version="1.11.0-beta.2" />
```

```
**Auto instrumentation image:** 
ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-dotnet:1.11.0
```

And 
```
**Auto instrumentation image:**
ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-dotnet:1.10.0
```

### Runtime Version

8.0

### Description

[Managed] [2025-04-08T18:06:26.5099505Z] [Warning] EventSource=OpenTelemetry-Sdk, Message=Measurements from Instrument 'db.client.connections.usage', Meter 'Npgsql' will be ignored. Reason: 'Instrument belongs to a Meter not subscribed by the provider.'. Suggested action: 'Use AddMeter to add the Meter to the provider.'

I used open telemetry operator with auto instrumentation.

### Steps to Reproduce

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: REDACTED
  name: REDACTED
spec:
  replicas: 1
  selector:
    matchLabels:
      app: REDACTED
  template:
    metadata:
      labels:
        app: REDACTED
      annotations:
        instrumentation.opentelemetry.io/inject-dotnet: observability/auto-instrumentation

Deploy .net 8 application with versions above.

### Expected Result

Tracings from ngpsql.

### Actual Result

[Managed] [2025-04-08T18:06:26.5099505Z] [Warning] EventSource=OpenTelemetry-Sdk, Message=Measurements from Instrument 'db.client.connections.usage', 

Meter 'Npgsql' will be ignored. Reason: 'Instrument belongs to a Meter not subscribed by the provider.'. 

Suggested action: 'Use AddMeter to add the Meter to the provider.' used open telemetry operator with auto instrumentation.

**Comment by Kielek** [comment]
I would not consider this as a bug, but rather as a feature requests. 1.11.0 and earlier does not natively support Npgql metrics. You can check it under https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/v1.11.0/docs/config.md#metrics-instrumentations

You can start processing it by setting `Npgsql` value to `OTEL_DOTNET_AUTO_METRICS_ADDITIONAL_SOURCES` env. var. It is documented under the same file as list of metrics.

Would you like to contribute native support to this project?

**Comment by RassK** [comment]
`Npgsql.OpenTelemetry` seems properly built without external dependencies (only OpenTelemetry.Api). 
Thinking if it's necessary to move it under OpenTelemetry contrib first... or go without the package reference in auto instrumentation side?

**Comment by Kielek** [comment]
Go without any reference to this package. Just listen on new metrics like for Npgsql traces or NServiceBus metrics and traces: https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/0491d670a83b7362f4162d4c5ad60d5243953a4e/src/OpenTelemetry.AutoInstrumentation/Configurations/EnvironmentConfigurationMetricHelper.cs#L32-L36

**Comment by Vinaum8** [comment]
> I would not consider this as a bug, but rather as a feature requests. 1.11.0 and earlier does not natively support Npgql metrics. You can check it under https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/v1.11.0/docs/config.md#metrics-instrumentations

strange, I've seen db statements work in granada tempo with my stack, but I don't remember the version.

**Comment by Vinaum8** [comment]
> You can start processing it by setting `Npgsql` value to `OTEL_DOTNET_AUTO_METRICS_ADDITIONAL_SOURCES` env. var. It is documented under the same file as list of metrics.

I tried this but it didn't work.

**Comment by Vinaum8** [comment]
> > You can start processing it by setting `Npgsql` value to `OTEL_DOTNET_AUTO_METRICS_ADDITIONAL_SOURCES` env. var. It is documented under the same file as list of metrics.
> 
> I tried this but it didn't work.

I'm doing more testing and will give you feedback.

**Comment by Vinaum8** [comment]
```
dotnet:
    env:
      - name: OTEL_DOTNET_AUTO_TRACES_GRPCNETCLIENT_INSTRUMENTATION_ENABLED
        value: 'true'
      - name: OTEL_DOTNET_AUTO_METRICS_PROCESS_INSTRUMENTATION_ENABLED
        value: 'true'
      - name: OTEL_DOTNET_AUTO_INSTRUMENTATION_ENABLED
        value: 'true'
      - name: OTEL_LOG_LEVEL
        value: debug
      - name: OTEL_DOTNET_AUTO_METRICS_ADDITIONAL_SOURCES
        value: Npgsql,Microsoft.EntityFrameworkCore
      - name: OTEL_DOTNET_AUTO_TRACES_ADDITIONAL_SOURCES
        value: Npgsql,Microsoft.EntityFrameworkCore
      - name: OTEL_METRICS_INSTRUMENTATION_OPTIONS__INCLUDED_METERS
        value: Npgsql,Microsoft.EntityFrameworkCore
      - name: OTEL_DOTNET_AUTO_METRICS_ADDITIONAL_METERS
        value: Npgsql
```

**I set up my auto instrumentation with these environment variables and everything worked.** 💯 

Also, I was using this parameter in my open telemetry collector:

[dropping-non-http-spans](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/filterprocessor/README.md#dropping-non-http-spans)

which was causing the dropping of spans that did not have the `http.request.method` attribute

Thanks for the support.
